[workspace]
resolver = "2"
members = [
  "apollo",
  "wl_common",
  "wl_server",
  "wl_spec",
  "wl_scanner",
  "wl_scanner_support",
  "wl_types",
  "wl_macros",
  "wl_io",
  "wl_io_traits",
  "wl_protocol",
  "crescent",
]
exclude = [
  "testbench"
]

[workspace.dependencies]
tracing = { version = "0.1", features = [ "release_max_level_off" ] }
hashbrown = "0.12"
futures-lite = "1.12.0"
futures-util = "0.3.24"
thiserror = "1.0.35"
derivative = "2.2.0"
dlv-list = { git = "https://github.com/yshui/dlv-list-rs" }
