binop_separator = "Back"
enum_discrim_align_threshold = 40
struct_field_align_threshold = 40
format_code_in_doc_comments = true
format_strings = true
indent_style = "Block"
match_arm_blocks = false
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = true
imports_granularity = "Crate"
newline_style = "Unix"
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
trailing_semicolon = false
use_field_init_shorthand = true
wrap_comments = true
