[package]
name = "crescent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.65"
futures-executor = "0.3.24"
futures-util = "0.3.24"
log = "0.4.17"
smol = "1.2.5"
tracing = { version = "0.1.36", features = ["release_max_level_off"] }
tracing-subscriber = "0.3.15"
wl_common = { version = "0.1.0", path = "../wl_common" }
wl_io = { version = "0.1.0", path = "../wl_io" }
wl_macros = { version = "0.1.0", path = "../wl_macros" }
wl_server = { version = "0.1.0", path = "../wl_server" }
