[package]
name = "wl_common"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-lite = "1.12"
serde = { version = "1.0", features = ["derive"] }
wl_io = { path = "../wl_io" }
wl_macros = { path = "../wl_macros" }

hashbrown.workspace = true
num-traits = "0.2.15"
