[package]
name = "wl_common"
version = "0.1.0"
edition = "2021"

[dependencies]
futures-lite = "1.12"
wl_io_traits = { path = "../wl_io_traits" }
wl_macros = { path = "../wl_macros" }

hashbrown.workspace = true
num-traits = "0.2.15"
