[package]
name = "wl_io"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-io = "1.9.0"
futures-lite = "1.11.0"
libc = "0.2.132"
nix = "0.25.0"
pin-project-lite = "0.2.9"
