[package]
name = "wl_scanner"
description = "Generate code from wayland protocol specifications"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
