[package]
name = "wl_spec"
description = "Parsing and representing wayland protocol files"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
quick-xml = "0.24.0"
thiserror = "1.0.33"
