[package]
name = "runa-wayland-spec-parser"
description = "Parsing and representing wayland protocol files"
repository = "https://github.com/yshui/runa"
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[dependencies]
quick-xml = "0.28.1"
thiserror.workspace = true
